### ISSUE TITLE
Make Dwolla Client Initialization Arguments Coherent

### ISSUE THREAD

**Issue by Jberlinsky** [Dwolla/dwolla-v2-ruby#17]
The Dwolla client initialization parameter name (`id`) is extremely confusing to someone coming into this codebase with significant OAuth experience. I strongly suggest that:

- The `id` parameter be updated to read `key`
- Documentation within this repository be updated, such that instead of `ENV["DWOLLA_ID"]` and the like, the Client is initialized with something like `ENV["DWOLLA_CONSUMER_KEY"]` or `ENV["DWOLLA_KEY"]`
- The sample bootstrapping code at https://gist.github.com/sausman/df58a196b3bc0381b0e8 should be updated for significant clarity
- The official Dwolla documentation should be updated for clarity. One example of this ambiguity is here: https://developers.dwolla.com/pages/sdks.html

**Comment by sausman** [comment]
Hey @Jberlinsky,

Sorry for the confusion, totally see where you're coming from. When I wrote this I was basing it off the terminology used in the [OAuth 2](https://tools.ietf.org/html/rfc6749#section-2.2) spec without realizing it changed from the OAuth 1 spec and some areas on our site (consumer key -> client id).

Working on an update now to make things more consistent. I will post back here once it's been merged. Thanks for the heads up!

**Comment by sausman** [comment]
Just released `1.2.0`, thanks again!
