### ISSUE TITLE
Method name clash for Funding Source

### ISSUE THREAD

**Issue by madAle** [Dwolla/dwolla-v2-ruby#26]
Hi, 

when retrieving a customer's Funding Source the "status" attribute/method clashes with Response#status (HTTP status code) and the latter is returned instead of Funding Source status (e.g "verified"). 

From API doc:
```ruby
funding_source_url = 'https://api-sandbox.dwolla.com/funding-sources/692486f8-29f6-4516-a6a5-c69fd2ce854c'

# Using DwollaV2 - https://github.com/Dwolla/dwolla-v2-ruby (Recommended)
funding_source = app_token.get funding_source_url
funding_source.name # => "Test checking account"

funding_source.status # => 200 instead of, for example "verified"
```

I dug a bit the code, but I didn't find an easy solution that does not interfere with the rest of the SDK... 

Knowing the issue, a workaround to get Funding Source's status may be something like this:

```ruby
require 'json'

fs_data = JSON.load funding_source.to_json
fs_status = fs_data["status"]  # =>  "verified"
```

**Comment by sausman** [comment]
Hey @madAle,

Thanks for letting us know. This conflict was resolved in #20 (version 2.0) by adding the `#response_status` and `#response_headers` methods to `DwollaV2::Response`.
