### ISSUE TITLE
Gem dependencies out of day

### ISSUE THREAD

**Issue by jskirst** [Dwolla/dwolla-v2-ruby#62]
The reliance on Faraday middleware makes this unusable on really any modern ruby application. Is Dwolla still alive/is this gem updated? If so, is there a way to remove the middleware dependency?

https://github.com/lostisland/faraday_middleware

**Comment by tarricsookdeo** [comment]
Hi @jskirst! Thanks for bringing this issue up. We are aware that the our Ruby SDK is dated and looking into updating it. Updating the SDK to remove dependence on Faraday Middleware is on the roadmap.

**Comment by javierjulio** [comment]
Note [this change was included in Faraday 1.10.0](https://github.com/lostisland/faraday/pull/1400) which should help here.

**Comment by tarricsookdeo** [comment]
@javierjulio thanks for this! I'll take a look at it.
