### ISSUE TITLE
Ruby 3.2+ Keywords Error In Lib/Client.rb

### ISSUE THREAD

**Issue by peterb-onramp** [Dwolla/dwolla-v2-ruby#67]
Our specs fail when updating to ruby 3.2. We traced the issue back to https://github.com/Dwolla/dwolla-v2-ruby/blob/980853368696d50b3d1c9e4cea0c310efa662f4e/lib/dwolla_v2/client.rb#L22-L25 not being keywords compliant.

https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

> Methods taking a rest parameter (like *args) and wishing to delegate keyword arguments through foo(*args) must now be marked with ruby2_keywords (if not already the case). In other words, all methods wishing to delegate keyword arguments through *args must now be marked with ruby2_keywords, with no exception. This will make it easier to transition to other ways of delegation once a library can require Ruby 3+. Previously, the ruby2_keywords flag was kept if the receiving method took *args, but this was a bug and an inconsistency. A good technique to find potentially missing ruby2_keywords is to run the test suite, find the last method which must receive keyword arguments for each place where the test suite fails, and use puts nil, caller, nil there. Then check that each method/block on the call chain which must delegate keywords is correctly marked with ruby2_keywords

To fix we add the '**' before the `opts` parameter and this resolved the issue.

**Comment by javierjulio** [comment]
This is the correct change and is safe for earlier versions. For the record, the samples in the README all use keyword arguments for the client initialization. You had an open PR for this, why did you close it? You should reopen and contribute that change!

**Comment by peterb-onramp** [comment]
Recreated PR here https://github.com/Dwolla/dwolla-v2-ruby/pull/68

**Comment by javierjulio** [comment]
Thanks! Now we just need to get a maintainer to run the PR checks so hopefully all checks out.

**Comment by ShreyaThapa** [comment]
Thanks for the PR, @peterb-onramp and @javierjulio for the review! The PR has been merged into main, and the changes will be reflected in the next release!
