### ISSUE TITLE
github.com/Dwolla/dwolla-v2-ruby/tree/44bea580123ad914b184e54c65f80d05600d3d3d#usage doesn't give correct scopes in uat

### ISSUE THREAD

**Issue by gpolyn** [Dwolla/dwolla-v2-ruby#9]
Seems that scopes can't be changed as [dwolla-v2 #usage](github.com/Dwolla/dwolla-v2-ruby/tree/44bea580123ad914b184e54c65f80d05600d3d3d#usage) suggests, at least not in sandbox environment.

Running the following, the only scope I get is `managecustomers`:

[gist.github.com/gpolyn/148ca150ea1bd19db282](https://gist.github.com/gpolyn/148ca150ea1bd19db282)

**Comment by sausman** [comment]
Hey @gpolyn, sorry I didn't notice this issue until now.

It sounds like you may need to edit your application's permissions to include the other scopes. You can do so by going to https://uat.dwolla.com/applications and clicking the "Edit Permissions" to the right of your application.

Hopefully that works, let me know if you still run into issues.
